# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfaster', '0003_auto_20170218_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
