# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfaster', '0008_auto_20170316_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='shipping_is_same',
        ),
        migrations.AddField(
            model_name='shipping',
            name='same_as_billing',
            field=models.BooleanField(default=False),
        ),
    ]
