# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterfaster', '0014_remove_shipping_same_as_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='user',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
