# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterfaster', '0018_auto_20170612_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterfaster.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterfaster.SubTopic'),
        ),
    ]
