# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfaster', '0019_auto_20170614_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(max_length=400),
        ),
    ]
