# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfaster', '0020_auto_20170615_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default='No description.', max_length=400),
        ),
    ]
