# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfaster', '0022_auto_20170615_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(default='No description.', max_length=275),
        ),
    ]
