# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='pid',
            field=models.IntegerField(),
        ),
    ]
