# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
