# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 17:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170324_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200, null=True)),
                ('img_path', models.CharField(default='sales/images/default.jpg', max_length=200)),
                ('size', django.contrib.postgres.fields.jsonb.JSONField(default=sales.models.Product.size_default, verbose_name='Size')),
            ],
        ),
    ]
