# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='pid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='sale_id',
            field=models.IntegerField(),
        ),
    ]
