# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20170411_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='pname',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchases',
            name='pprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
